// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

library LibInteractiveObjects {
    struct InteractiveObject {
        string name;
        int32 x;
        int32 y;
        int32 width;
        int32 height;
    }

    function getAllInteractiveObjects() internal pure returns (InteractiveObject[] memory) {
        InteractiveObject[] memory allInteractiveObjects = new InteractiveObject[](89);
        allInteractiveObjects[0] = InteractiveObject('Desk', 110, 45, 3, 4);
        allInteractiveObjects[1] = InteractiveObject('Desk', 116, 45, 2, 2);
        allInteractiveObjects[2] = InteractiveObject('Gambling table', 80, 20, 6, 3);
        allInteractiveObjects[3] = InteractiveObject('Gambling table', 85, 24, 5.0, 3);
        allInteractiveObjects[4] = InteractiveObject('Gambling table', 87, 29, 6, 3);
        allInteractiveObjects[5] = InteractiveObject('Gambling table', 80, 28, 6, 3);
        allInteractiveObjects[6] = InteractiveObject('Gambling table', 72, 29, 6, 3);
        allInteractiveObjects[7] = InteractiveObject('Gambling table', 75, 24, 6, 3);
        allInteractiveObjects[8] = InteractiveObject('Artwork', 125, 44, 5, 2);
        allInteractiveObjects[9] = InteractiveObject('Artwork', 131, 44, 4, 5);
        allInteractiveObjects[10] = InteractiveObject('Television', 131, 72, 2, 1);
        allInteractiveObjects[11] = InteractiveObject('Table', 124, 69, 3, 2);
        allInteractiveObjects[12] = InteractiveObject('Table', 126, 80, 3, 1);
        allInteractiveObjects[13] = InteractiveObject('Range', 130, 80, 3, 1);
        allInteractiveObjects[14] = InteractiveObject('Fridge', 133, 80, 1, 1);
        allInteractiveObjects[15] = InteractiveObject('Bathtub', 132, 76, 2, 1);
        allInteractiveObjects[16] = InteractiveObject('Sink', 128, 78, 2, 1);
        allInteractiveObjects[17] = InteractiveObject('Toilet', 130, 78, 1, 1);
        allInteractiveObjects[18] = InteractiveObject('Bookshelf', 127, 85, 3, 1);
        allInteractiveObjects[19] = InteractiveObject('Bed', 132, 86, 2, 1);
        allInteractiveObjects[20] = InteractiveObject('Table', 107, 68, 3, 2);
        allInteractiveObjects[21] = InteractiveObject('Table', 107, 89, 3, 1);
        allInteractiveObjects[22] = InteractiveObject('Bed', 118, 86, 2, 1);
        allInteractiveObjects[23] = InteractiveObject('Bed', 118, 79, 2, 2);
        allInteractiveObjects[24] = InteractiveObject('Bed', 118, 73, 1, 1);
        allInteractiveObjects[25] = InteractiveObject('Bed', 118, 66, 2, 2);
        allInteractiveObjects[26] = InteractiveObject('Bathtub', 108, 75, 2, 2);
        allInteractiveObjects[27] = InteractiveObject('Bathtub', 104, 79, 2, 2);
        allInteractiveObjects[28] = InteractiveObject('Sink', 108, 79, 2, 1);
        allInteractiveObjects[29] = InteractiveObject('Sink', 105, 74, 2, 1);
        allInteractiveObjects[30] = InteractiveObject('Toilet', 107, 79, 1, 1);
        allInteractiveObjects[31] = InteractiveObject('Toilet', 107, 74, 1, 1);
        allInteractiveObjects[32] = InteractiveObject('Bookshelf', 112, 85, 4, 1);
        allInteractiveObjects[33] = InteractiveObject('Bookshelf', 111, 76, 4, 1);
        allInteractiveObjects[34] = InteractiveObject('Bookshelf', 113, 66, 2, 1);
        allInteractiveObjects[35] = InteractiveObject('Bookshelf', 118, 89, 2, 1);
        allInteractiveObjects[36] = InteractiveObject('Table', 100, 74, 3, 2);
        allInteractiveObjects[37] = InteractiveObject('Table', 100, 81, 3, 2);
        allInteractiveObjects[38] = InteractiveObject('Television', 94, 88, 4, 2);
        allInteractiveObjects[39] = InteractiveObject('Television', 102, 68, 1, 2);
        allInteractiveObjects[40] = InteractiveObject('Range', 105, 66, 5, 1);
        allInteractiveObjects[41] = InteractiveObject('Fridge', 104, 66, 1, 1);
        allInteractiveObjects[42] = InteractiveObject('Fridge', 109, 87, 1, 1);
        allInteractiveObjects[43] = InteractiveObject('Range', 106, 87, 3, 1);
        allInteractiveObjects[44] = InteractiveObject('Table', 80, 69, 3, 2);
        allInteractiveObjects[45] = InteractiveObject('Table', 42, 63, 4, 2);
        allInteractiveObjects[46] = InteractiveObject('Table', 38, 83, 3, 1);
        allInteractiveObjects[47] = InteractiveObject('Table', 35, 67, 3, 1);
        allInteractiveObjects[48] = InteractiveObject('Television', 87, 72, 3, 1);
        allInteractiveObjects[49] = InteractiveObject('Television', 45, 67, 3, 1);
        allInteractiveObjects[50] = InteractiveObject('Television', 45, 83, 3, 1);
        allInteractiveObjects[51] = InteractiveObject('Range', 83, 80, 4, 1);
        allInteractiveObjects[52] = InteractiveObject('Range', 36, 64, 4, 1);
        allInteractiveObjects[53] = InteractiveObject('Range', 37, 81, 4, 1);
        allInteractiveObjects[54] = InteractiveObject('Bookshelf', 83, 89, 4, 1);
        allInteractiveObjects[55] = InteractiveObject('Bookshelf', 28, 81, 4, 1);
        allInteractiveObjects[56] = InteractiveObject('Bookshelf', 32, 67, 2, 1);
        allInteractiveObjects[57] = InteractiveObject('Bookshelf', 28, 61, 2, 1);
        allInteractiveObjects[58] = InteractiveObject('Bathtub', 88, 76, 2, 1);
        allInteractiveObjects[59] = InteractiveObject('Sink', 84, 78, 2, 1);
        allInteractiveObjects[60] = InteractiveObject('Toilet', 86, 78, 1, 1);
        allInteractiveObjects[61] = InteractiveObject('Fridge', 89, 80, 1, 3);
        allInteractiveObjects[62] = InteractiveObject('Bed', 87, 86, 3, 1);
        allInteractiveObjects[63] = InteractiveObject('Bed', 32, 75, 2, 1);
        allInteractiveObjects[64] = InteractiveObject('Bed', 28, 66, 3, 2);
        allInteractiveObjects[65] = InteractiveObject('Bed', 32, 58, 2, 1);
        allInteractiveObjects[66] = InteractiveObject('Sink', 38, 57, 2, 1);
        allInteractiveObjects[67] = InteractiveObject('Toilet', 40, 57, 1, 1);
        allInteractiveObjects[68] = InteractiveObject('Sink', 38, 74, 2, 1);
        allInteractiveObjects[69] = InteractiveObject('Toilet', 40, 74, 1, 1);
        allInteractiveObjects[70] = InteractiveObject('Fridge', 36, 81, 1, 1);
        allInteractiveObjects[71] = InteractiveObject('Fridge', 35, 64, 1, 1);
        allInteractiveObjects[72] = InteractiveObject('Bathtub', 35, 58, 2, 1);
        allInteractiveObjects[73] = InteractiveObject('Bathtub', 35, 75, 2, 1);
        allInteractiveObjects[74] = InteractiveObject('Cafe table', 72, 38, 3, 2);
        allInteractiveObjects[75] = InteractiveObject('Cafe table', 80, 38, 3, 2);
        allInteractiveObjects[76] = InteractiveObject('Cafe table', 79, 42, 3, 2);
        allInteractiveObjects[77] = InteractiveObject('Cafe table', 74, 42, 3, 2);
        allInteractiveObjects[78] = InteractiveObject('Cafe table', 77, 47, 3, 2);
        allInteractiveObjects[79] = InteractiveObject('Cafe table', 71, 46, 2, 3);
        allInteractiveObjects[80] = InteractiveObject('Ordering', 74, 35, 6, 1);
        allInteractiveObjects[81] = InteractiveObject('Bar', 87, 35, 4, 1);
        allInteractiveObjects[82] = InteractiveObject('Bar table', 91, 37, 3, 2);
        allInteractiveObjects[83] = InteractiveObject('Bar table', 91, 47, 3, 2);
        allInteractiveObjects[84] = InteractiveObject('Bar table', 84, 47, 3, 2);
        allInteractiveObjects[85] = InteractiveObject('Bar table', 88, 40, 4, 2);
        allInteractiveObjects[86] = InteractiveObject('Bar table', 88, 44, 4, 2);
        allInteractiveObjects[87] = InteractiveObject('Dance floor', 84, 37, 3, 8);
        allInteractiveObjects[88] = InteractiveObject('Goal', 68, 88, 4, 1);
        return allInteractiveObjects;
    }
}